apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: pyserver
  name: pyserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pyserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: pyserver
    spec:
      containers:
        - args:
            - python
            - -m
            - http.server
            - "8000"
          image: python:3.13.5-slim
          name: pyserver
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: pyserver-cm0
          workingDir: /app
      restartPolicy: Always
      volumes:
        - configMap:
            name: pyserver-cm0
          name: pyserver-cm0
